version: "0.5"

nodes:
  build:
    matrix:
      dense:
        dimensions:
          - - env:
                RELEASE: ""
            - env:
                RELEASE: "--release"
    tasks:
      - script: |
          set -e
          cargo build $FEATURES $RELEASE

  test:
    tasks:
      - script: |
          set -e
          cargo test
  fmt:
    tasks:
      - script: |
          set -e
          cargo +nightly fmt

  "hook:pre-commit":
    tasks:
      - script: |
          set -e
          cargo +nightly fmt -- --check

  "hook:pre-push":
    pre:
      - build
      - test
    tasks: []
